export default [
  {
    path: 'Rechatter',
    load: () => import(/* webpackChunkName: "p_rechatter" */ '@/pages/Rechatter'),
    componentName: 'rechatter',
    index: undefined,
    id: 'Rechatter',
    exact: true,
    exports: ["default"],
  },{
    path: 'UserList',
    load: () => import(/* webpackChunkName: "p_userlist" */ '@/pages/UserList'),
    componentName: 'userlist',
    index: undefined,
    id: 'UserList',
    exact: true,
    exports: ["default"],
  },{
    path: 'Chatter',
    load: () => import(/* webpackChunkName: "p_chatter" */ '@/pages/Chatter'),
    componentName: 'chatter',
    index: undefined,
    id: 'Chatter',
    exact: true,
    exports: ["default"],
  },{
    path: '',
    load: () => import(/* webpackChunkName: "p_index" */ '@/pages/index'),
    componentName: 'index',
    index: true,
    id: 'index',
    exact: true,
    exports: ["default"],
  },
];
